import "styles/globals.css";
import { SiteContextProvider } from "@/lib/context";

import Layout from "components/layout/layout";
import { isBrowser } from "@/lib/helpers";

import { lato, quicksand } from "@/lib/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (isBrowser) {
  console.groupCollapsed(
    "%c🦤 Site Credits",
    "display:block;padding:0.125em 1em;font-family:courier;font-size:14px;font-weight:bold;line-height:2;text-transform:uppercase;background:black;color:white;"
  );
  console.log(
    "%cDesign copied from  \n– https://boostify-nesst.myshopify.com/",
    "display:block;font-family:courier;font-size:12px;font-weight:bold;line-height:1;color:black;"
  );
  console.log(
    "%c🦤 Onnum tnnalle seatta",
    "display:block;font-family:courier;font-size:12px;font-weight:bold;line-height:1;color:black;"
  );
  console.groupEnd();
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const Site = ({ children }: any): JSX.Element => {
    return (
      // <LazyMotion features={domAnimation}>
      //   <AnimatePresence
      //     mode="wait"
      //     onExitComplete={() => {
      //       document.body.classList.remove("overflow-hidden");
      //     }}
      //   >
      <Layout>{children}</Layout>
      //   </AnimatePresence>
      // </LazyMotion>
    );
  };

  return (
    <html lang="en">
      <body
        className={`${lato.className} ${lato.variable} ${quicksand.variable}`}
      >
        <SiteContextProvider>
          {" "}
          <Site>{children}</Site>
        </SiteContextProvider>
      </body>
    </html>
  );
}
